// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package go_tokenmgmt_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenManagementClient is the client API for TokenManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenManagementClient interface {
	CreateNewToken(ctx context.Context, in *NewToken, opts ...grpc.CallOption) (*Token, error)
	GetToekns(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
	DropToken(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*EmptyToken, error)
	WriteToken(ctx context.Context, in *NewToken, opts ...grpc.CallOption) (*Token, error)
}

type tokenManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenManagementClient(cc grpc.ClientConnInterface) TokenManagementClient {
	return &tokenManagementClient{cc}
}

func (c *tokenManagementClient) CreateNewToken(ctx context.Context, in *NewToken, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/tokenmgmt.TokenManagement/CreateNewToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenManagementClient) GetToekns(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/tokenmgmt.TokenManagement/GetToekns", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenManagementClient) DropToken(ctx context.Context, in *TokenInfo, opts ...grpc.CallOption) (*EmptyToken, error) {
	out := new(EmptyToken)
	err := c.cc.Invoke(ctx, "/tokenmgmt.TokenManagement/DropToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenManagementClient) WriteToken(ctx context.Context, in *NewToken, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/tokenmgmt.TokenManagement/WriteToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenManagementServer is the server API for TokenManagement service.
// All implementations must embed UnimplementedTokenManagementServer
// for forward compatibility
type TokenManagementServer interface {
	CreateNewToken(context.Context, *NewToken) (*Token, error)
	GetToekns(context.Context, *Token) (*Token, error)
	DropToken(context.Context, *TokenInfo) (*EmptyToken, error)
	WriteToken(context.Context, *NewToken) (*Token, error)
	mustEmbedUnimplementedTokenManagementServer()
}

// UnimplementedTokenManagementServer must be embedded to have forward compatible implementations.
type UnimplementedTokenManagementServer struct {
}

func (UnimplementedTokenManagementServer) CreateNewToken(context.Context, *NewToken) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewToken not implemented")
}
func (UnimplementedTokenManagementServer) GetToekns(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetToekns not implemented")
}
func (UnimplementedTokenManagementServer) DropToken(context.Context, *TokenInfo) (*EmptyToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropToken not implemented")
}
func (UnimplementedTokenManagementServer) WriteToken(context.Context, *NewToken) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WriteToken not implemented")
}
func (UnimplementedTokenManagementServer) mustEmbedUnimplementedTokenManagementServer() {}

// UnsafeTokenManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenManagementServer will
// result in compilation errors.
type UnsafeTokenManagementServer interface {
	mustEmbedUnimplementedTokenManagementServer()
}

func RegisterTokenManagementServer(s grpc.ServiceRegistrar, srv TokenManagementServer) {
	s.RegisterService(&TokenManagement_ServiceDesc, srv)
}

func _TokenManagement_CreateNewToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagementServer).CreateNewToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenmgmt.TokenManagement/CreateNewToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagementServer).CreateNewToken(ctx, req.(*NewToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenManagement_GetToekns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagementServer).GetToekns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenmgmt.TokenManagement/GetToekns",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagementServer).GetToekns(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenManagement_DropToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagementServer).DropToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenmgmt.TokenManagement/DropToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagementServer).DropToken(ctx, req.(*TokenInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenManagement_WriteToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenManagementServer).WriteToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenmgmt.TokenManagement/WriteToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenManagementServer).WriteToken(ctx, req.(*NewToken))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenManagement_ServiceDesc is the grpc.ServiceDesc for TokenManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tokenmgmt.TokenManagement",
	HandlerType: (*TokenManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewToken",
			Handler:    _TokenManagement_CreateNewToken_Handler,
		},
		{
			MethodName: "GetToekns",
			Handler:    _TokenManagement_GetToekns_Handler,
		},
		{
			MethodName: "DropToken",
			Handler:    _TokenManagement_DropToken_Handler,
		},
		{
			MethodName: "WriteToken",
			Handler:    _TokenManagement_WriteToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/token.proto",
}
